### PR TITLE
Prerelease v4.0.0-0

### PR DESCRIPTION
**Pull request by nateplusplus**
- Minified assets for CDN
- Switched to TypeScript

### CODE REVIEW

**Comment by nateplusplus** [comment]
@arturovt - It looks like when I merged the CDN stuff in with typescript, I'm getting some errors when trying to build. I think because the CDN stuff is trying to use JS/babel. I get this error:

```bash
src/index.js → dist/umd/pushin.min.js...
[!] Error: Could not resolve entry module (src/index.js).
Error: Could not resolve entry module (src/index.js).
    at error (/Users/nathanblair/Sites/pushIn-js/node_modules/rollup/dist/shared/rollup.js:198:30)
    at ModuleLoader.loadEntryModule (/Users/nathanblair/Sites/pushIn-js/node_modules/rollup/dist/shared/rollup.js:22436:20)
    at async Promise.all (index 0)
```

I tried changing the entry point to `src/index.ts`, but then it has issues importing helpers.ts. I wanted to run this by you before I went too deep down that rabbit hole.

**Comment by arturovt** [comment]
Yeah, I knew those 2 PRs are incompatible

**Comment by arturovt** [comment]
I’ll fix it

**Comment by arturovt** [comment]
Should I make a pr to this branch?

**Comment by nateplusplus** [comment]
@arturovt Thanks for getting this working, looks great! I also added minified CSS for the CDN.

Considering all the ideas we have in the works, I think I will release this as a pre-release to v4. We can continue working on some of the other big improvements that we've discussed and release them all in v4 once ready.

**Pull request merged**
