### PR TITLE
Tree-shake development only code

### PR DESCRIPTION
**Pull request by arturovt**
Also fixed invalid JSDoc comments and ESLint issues.

### CODE REVIEW

**Comment by nateplusplus** [comment]
Another great contribution, thank you @arturovt!

I think the `showDebugger` function could also go into the helpers file, since I feel like it's essentially another helper function for development.

I only have one concern here: For the average consumer of this code, I imagine they will simply be downloading the production build and using it in their project (whether that's through NPM or a manual download). I'm concerned that means they will not be able to use the debugger tool, as well as not see error if they're using the code improperly.

The "debugger" may be a misnomer, because it does sound like something used to develop this module. However, the intention behind the debugger tool is to give people an easy way to decide at what pixel value they want layers to appear and disappear from view (otherwise it's just a guessing game). If we hide it behind a different webpack mode (like `development` or something), would that mean they would need to go into the node_modules folder and rebuild the package in development mode?

Here is an example of the debugger tool in action: https://nateplusplus.github.io/pushIn-js/responsive.html

Does this make sense? Let me know what you think, I would love any feedback on this.

**Comment by arturovt** [comment]
Well, we should not publish minified files. This is one of the best practices:

> **Minification:** This is slowly becoming less relevant for package publishers as build tools will often handle this for our end users.

Consumers should be able to read and debug the library code, e.g. put breakpoints, see functions that throw exceptions, etc.

Ideally, we should decouple debugger from the main class, e.g. this will live in a subpackage `pushin/debug`.

**Comment by arturovt** [comment]
I can put it in a draft after we switch to Rollup.

**Comment by nateplusplus** [comment]
Ooo I love that idea of a subpackage and I agree 100% with not publishing minified code too! Sounds great, thanks!

**Pull request closed without merging**
